### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by Bhavay-2001** [lilygeorgescu/UBnormal#13]
Hello @lilygeorgescu, I'm trying to download the data from the google drive you provided and the file downloads but it is downloaded as a normal file and not a zip file and when i try to open it, it says that the file is corrupt. Can you tell what's wrong and how can i solve it?

**Comment by lilygeorgescu** [comment]
Hi,

I did not modify the archive since the last year and many others succeeded to download and extract it. However, I am aware that there is a problem on Linux with big archives,  if you are using Linux or Mac, please see https://github.com/lilygeorgescu/UBnormal/issues/1 for references and fix.

Best,
Lili
